version: "3"

services:
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=_egorgdYarov0309
      - POSTGRES_DB=postgres
    volumes:
      - db-data:/var/lib/postgres/data
volumes:
  db-data:
